#  this code is created by command                protoc --python_out=. notification_service.proto



# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1anotification_service.proto\"\x88\x01\n\x13NotificationMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\trecipient\x18\x04 \x01(\t\x12\x0f\n\x07sent_at\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONMESSAGE']._serialized_start=31
  _globals['_NOTIFICATIONMESSAGE']._serialized_end=167
# @@protoc_insertion_point(module_scope)



# ================================================================

# # this code is generated by     chat


# # Generated by the protocol buffer compiler. DO NOT EDIT!
# # source: notification_service.proto

# from google.protobuf import descriptor as _descriptor
# from google.protobuf import message as _message
# from google.protobuf import reflection as _reflection
# from google.protobuf import symbol_database as _symbol_database
# # @@protoc_insertion_point(imports)

# _sym_db = _symbol_database.Default()

# DESCRIPTOR = _descriptor.FileDescriptor(
#     name='notification_service.proto',
#     package='',
#     syntax='proto3',
#     serialized_options=None,
#     create_key=_descriptor._internal_create_key,
#     serialized_pb=b'\n\x1anotification_service.proto\"\x8c\x01\n\x12NotificationMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x11\n\trecipient\x18\x04 \x01(\t\x12\x0f\n\x07sent_at\x18\x05 \x01(\t\x12\x0f\n\x07version\x18\x06 \x01(\t\x12\x11\n\tchecksum\x18\x07 \x01(\t\x62\x06proto3'
# )


# _NOTIFICATIONMESSAGE = _descriptor.Descriptor(
#     name='NotificationMessage',
#     full_name='NotificationMessage',
#     filename=None,
#     file=DESCRIPTOR,
#     containing_type=None,
#     fields=[
#         _descriptor.FieldDescriptor(
#             name='id', full_name='NotificationMessage.id', index=0,
#             number=1, type=5, cpp_type=1, label=1,
#             has_default_value=False, default_value=0,
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='title', full_name='NotificationMessage.title', index=1,
#             number=2, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='message', full_name='NotificationMessage.message', index=2,
#             number=3, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='recipient', full_name='NotificationMessage.recipient', index=3,
#             number=4, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='sent_at', full_name='NotificationMessage.sent_at', index=4,
#             number=5, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='version', full_name='NotificationMessage.version', index=5,
#             number=6, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#         _descriptor.FieldDescriptor(
#             name='checksum', full_name='NotificationMessage.checksum', index=6,
#             number=7, type=9, cpp_type=9, label=1,
#             has_default_value=False, default_value=str(""),
#             message_type=None, enum_type=None, containing_type=None,
#             is_extension=False, extension_scope=None,
#             serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
#     ],
#     extensions=[
#     ],
#     nested_types=[],
#     enum_types=[
#     ],
#     serialized_options=None,
#     is_extendable=False,
#     syntax='proto3',
#     extension_ranges=[],
#     oneofs=[
#     ],
#     serialized_start=28,
#     serialized_end=168,
# )

# DESCRIPTOR.message_types_by_name['NotificationMessage'] = _NOTIFICATIONMESSAGE
# _sym_db.RegisterFileDescriptor(DESCRIPTOR)

# NotificationMessage = _reflection.GeneratedProtocolMessageType('NotificationMessage', (_message.Message,), {
#     'DESCRIPTOR': _NOTIFICATIONMESSAGE,
#     '__module__': 'notification_service_pb2'
#     # @@protoc_insertion_point(class_scope:NotificationMessage)
# })
# _sym_db.RegisterMessage(NotificationMessage)

# # @@protoc_insertion_point(module_scope)


# ============================================================================

